local:
  radius: 100
  message: "L %player% » %message%"
  nobody-nearby: "В радиусе %radius% не кого нету!"

global:
  message: "G %player% » %message%"
  trigger: "!"

misc:
  permission: "У вас нет прав!"
  spy: "[SPY] %player% » %message%"
  only-player: "Команда только для игроков"
  help: "Nerovix v1.0 
  \n/nchat reload - перезагрузка конфига 
  \n/nchat clear - очистка чата"